### ISSUE TITLE
HTTP 404  issue

### ISSUE THREAD

**Issue by StefanoSanfilippo** [GlobalDataLab/R-data-api#3]
I am trying a very simple request. 
When execute `gdl_request(session)`, I get the following errror message: 
```
_Error in `req_perform()`:
! HTTP 404 Not Found.
• Page not found_
```

```
session <- gdl_session(Sys.getenv("****************"))

# Customize parameters 
session <- set_dataset(session, 'shdi')

session <- set_country(session, "ESP")
# Finally, request the data from GDL 
sp <- gdl_request(session)
```

Any idea or suggestion?
Thanks

**Comment by AaronVanGeffen** [comment]
Hi Stefano,

This appears to be due to not specifying an indicator to retrieve. While you've specified the dataset, `shdi`, this dataset contains several indicators. Confusingly, the main indicator is also called `shdi`.

The following works for me:
```R
shdi <- session |>
  set_dataset('shdi') |>
  set_indicator('shdi') |>
  set_country('ESP') |>
  gdl_request()
```

NB: The `|>` is the pipe operator. You might have seen this written as `%>%` in older scripts as well.

**Comment by StefanoSanfilippo** [comment]
Hi Aaron,
Thank you! It was that the problem. A 'first lesson ' mistake!
I am studiyng the resources delivered by *Global Data Lab* and trying to learn to use this library.
Very interesting!
Thanks!
